export const CHANGE_TEST = 'CHANGE_TEST';
export const CHANGE_COUNT_INC = 'CHANGE_COUNT_INC';
export const CHANGE_COUNT_DECR = 'CHANGE_COUNT_DECR';
export const CHANGE_COUNT_VALUE = 'CHANGE_COUNT_VALUE';
export const SET_AUTH = 'SET_AUTH';

export const GET_USERS = 'GET_USERS';
export const GET_USERS_LOADING = 'GET_USERS_LOADING';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';

export const GET_COMMENTS = 'GET_COMMENTS';
export const GET_COMMENTS_LOADING = 'GET_COMMENTS_LOADING';
export const GET_COMMENTS_ERROR = 'GET_COMMENTS_ERROR';

export const GET_WEATHER = 'GET_WEATHER';
export const GET_WEATHER_ERROR = 'GET_WEATHER_ERROR';